# Generated by Django 3.0.8 on 2020-07-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0002_auto_20200721_1922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
