# Generated by Django 3.0.8 on 2020-08-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0003_stock_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(max_length=50)),
                ('transaction_amount', models.IntegerField(default='0')),
                ('timestamp', models.DateTimeField(null=True)),
                ('item_name', models.CharField(max_length=50)),
            ],
        ),
    ]
